### ISSUE TITLE
Wrong syntax?

### ISSUE THREAD

**Issue by SoNic1967** [abcd567a/ubuntu#1]
~$ sudo wget -O /etc/apt/sources.list.d/abcd567a.list
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.

**Comment by abcd567a** [comment]
Please copy-paste full command. You copy-pasted only 1st half the command,  and missed the 2nd half. 

You copy-pasted this part:
`sudo wget -O /etc/apt/sources.list.d/abcd567a.list `

You missed this part:
`https://raw.githubusercontent.com/abcd567a/ubuntu/master/abcd567a.list`
